### ISSUE TITLE
Implemented without raspberry pi

### ISSUE THREAD

**Issue by TimonPeng** [roscoe81/Doorbell-Monitor#4]
I'm thinking if it could run on its own or arduino, using a doorbell cable to provide power, because I observed 5V above it.

**Comment by TimonPeng** [comment]
Esp8266 is good choice if it's works, support with homekit easily.

**Comment by roscoe81** [comment]
That might be true @TimonPeng but I don’t know enough about the Esp8266 to verify if it would be a good choice. The project does use one USB sound card to provide the SIP audio connection for remote manual answering and for sending the pre-recorded automatic answering message. It also uses one USB video capture card to provide SIP video for remote manual answering and to record a still photo of visitors when they ring the doorbell. Those two factors, combined with the need to easily support SIP calls with Linphone and the Raspberry Pi’s extensive Python support steered me towards the Raspberry Pi. On the topic of power, the project uses a power supply to convert the intercom system’s 19 volt power supply to 5V.

**Comment by TimonPeng** [comment]
Oh, sorry, I forgot about the video and audio.

**Comment by TimonPeng** [comment]
We can communicate through IM? Like telegram or whatsapp.

**Comment by roscoe81** [comment]
No problem about forgetting the audio/video @TimonPeng , that aspect isn't documented clearly in the project. I don't really want to go down an IM path. Good luck with your projects.

**Comment by TimonPeng** [comment]
Cheers!

**Comment by TimonPeng** [comment]
Did you read video and send audio through the Fermax wire directly? I don't understand this part particularly.

**Comment by roscoe81** [comment]
I've just added the relevant schematic to the Schematics and Photos Folder of this repo. Here's a copy for easy reference. Hope that helps to clarify for you.
![Northcliff_Doorbell_Video_Audio_Power](https://user-images.githubusercontent.com/37389643/70112844-e75b6780-16aa-11ea-80d9-b9c84d21d43a.png)

**Comment by TimonPeng** [comment]
I'm confused about which wire is DC in? 1 or 5? or someone else?

1. Lock
2. Mic
3. GND
4. Call
5. Not used
6. Speaker

Is correct?

**Comment by roscoe81** [comment]
They’re two wires, marked + and - that supplies 18 volts. You can see them in the Firmax documentation and they’re marked on the handset’s termination board

**Comment by TimonPeng** [comment]
Oh, shit, we are in a different situation, my doorbell don't have video features, audio here only. I don't have extra power wires, so I can only try to get power from these five lines, or use external power supply.

**Comment by roscoe81** [comment]
It does look like the audio-only setup will require external power and it’s quite different from the setup with video features.

**Comment by TimonPeng** [comment]
Excuse me, I'd like to ask another question. I used arduino to read the wire 4 voltage, but there was no change when I rang the bell. Do you know the possible reason?

```
void setup() {
  Serial.begin(115200);
}

void loop() {
  int lightLevel = analogRead(A0);
  float voltage = lightLevel * (5.0 / 1024.0);
  Serial.println(voltage);
  delay(100);
}
```

Thank you so much.

**Comment by roscoe81** [comment]
That’s because the bell signal is low voltage AC. You’ll need to use the electronics (optocoupler plus R/C components) that are in my schematic between wire 4 and GPIO 24 of the Raspberry Pi. That circuit detects the AC bell signal and converts it to a DC bell/no bell signal.

**Comment by rafacampoamor** [comment]
> ![Northcliff_Doorbell_Video_Audio_Power](https://user-images.githubusercontent.com/37389643/70112844-e75b6780-16aa-11ea-80d9-b9c84d21d43a.png)
> 

Hi!

Sorry, I don't know much about this but I'm wondering if this schematics could be used with, for example, a Ring Intercom device (which officially doesn't support my Fermax videooppener, which I know the official Fermax add-on –Fermax Wi-Box— does, but doesn't support Apple HomeKit). 

I don't know if the "unsupported status" is because of electronics or may be some software issue involved. 

I just want to connect my video-oppener to HomeKit and be able to receive calls, talk a see video, and open the door, and I'm looking for options (as I don't find any that does all these functions yet). 

Thank you for your time and support 😊
