### ISSUE TITLE
Video feed

### ISSUE THREAD

**Issue by reverse13** [roscoe81/Doorbell-Monitor#5]
Great project! This was the only information I could find about converting a fermax vds feed into  digital, I’m trying to do something similar, my intercom receiver doesn’t have a video Input, but the wire is there and there is a camera on the buildings intercom, my idea is to convert that signal to digital and either send it via WiFi to a mobile device, or simply make a custom display for it, did you connect the vds wires directly to the usb vídeo card? If so what capture card did you use? I couldn’t quite see the model in the picture.
Kind regards!

**Comment by roscoe81** [comment]
Many thanks for the feedback. I used an EasyCap Adapter/Converter to capture the video, directly connected to wires V and M (shield) on the doorstation.

These are the commands I used to set up EasyCap on the Raspberry Pi.
•	wget https://github.com/gkaindl/ambi-tv/archive/master.zip
•	unzip master -zip
•	cd ambi-tv-master
•	cd misc
•	sudo bash get-kernel-source.sh
•	cd usbtv-driver
•	make
•	sudo mkdir -p  /lib/modules.3.6.11+/extra
•	sudo cp usbtv.ko /lib/modules/3.6.11+/extra
•	sudo depmod 3.6.11+
•	sudo modprobe videobuf2_core
•	sudo modprobe usbtv
•	v412-ctl –list-devices /dev/video0

Hope that helps and good luck.
