### ISSUE TITLE
Question about the door opening component

### ISSUE THREAD

**Issue by Soldiiier** [roscoe81/Doorbell-Monitor#6]
Hello, I am interested in doing a similar task for the door opening component.
Is the door open command sent via the data bus? how do you learn what the command/bits are, and are they cycled?

**Comment by roscoe81** [comment]
There is no data bus on the Fermax 4 + N Electronic Door Entry System. Therefore there are no commands/bits to learn and the door is opened by a relay contact that joins Wires 1 and 3 of the door station, as shown in the schematic [here](https://github.com/roscoe81/Doorbell-Monitor/blob/master/Schematics%20and%20Photos/Doorbell%202_schem.png)
