### ISSUE TITLE
Video feed Comelit 4600w

### ISSUE THREAD

**Issue by MarcosAndre** [roscoe81/Doorbell-Monitor#7]
Hi,
Awesome ideas and project! Congrats!

I'm thinking to do the same on my door system (version: Comelit 4600w). But I'm struggling with the video feed. The Comelit 4600w also have a coaxial video cable, but when I wired it to my easyCap capture device I don't have a signal (always blank). Do you have any recommendation? Could be related to some missing software setting or hardware? 

For now, I'm trying to get the video feed on my windows computer just to test it, then I'm thinking to use the Pi.

![1](https://user-images.githubusercontent.com/1064877/106609644-b4865b00-655d-11eb-87d5-6d7f2027fbab.jpg)
![2](https://user-images.githubusercontent.com/1064877/106609649-b51ef180-655d-11eb-97ae-aa0f6fe9b9db.jpg)
![3](https://user-images.githubusercontent.com/1064877/106609652-b5b78800-655d-11eb-96ad-edc38ed4debb.jpg)

Thanks again for sharing your code and project!

Regards,
Marcos André

**Comment by MarcosAndre** [comment]
I've noticed the problem, the video needs to be activated on the doorbell system.

Thanks anyway

**Comment by JoaoFilipeResende** [comment]
Did you manage to get it to work? I'm currently trying to understand the electrical diagram of it.
